"""Build the source-backed, bounded report manifest from offline audit evidence."""
import json
from pathlib import Path
import duckdb
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "reports/football-audit-20261009"

# Each issue separates observation, remedy, risk and model-change authority.
FINDINGS = [
    ("P0", "Confirmed identity defect", "Provider team aliases create false promotions",
     "The stored board contains Matthew Stafford twice: GSIS 00-0026498 on LA (not depth-verified), and depth:matthew stafford on LAR (verified). The second row has NaN forecasts. Other Rams also have name-generated promotion rows.",
     "SportsDataIO joins use raw team strings; nflverse uses LA. Names also differ through Sr./Jr./III suffixes.",
     "Implemented LAR→LA canonicalization in game/depth normalization and joins. Rebuild a staged snapshot; resolve name-generated IDs through an explicit stable-ID crosswalk before migrating saved assignments.",
     "Restores correct history and starter recognition; prevents duplicate fake rookies. Medium data-join risk: future correctly matched inputs can change outputs without changing the formula.", "No formula change. Do not silently migrate saved roster IDs.", "dashboard/providers/sportsdataio.py:normalize_games, normalize_depth_charts, add_depth_chart_promotions, enrich_board"),
    ("P0", "Confirmed software defect", "Historical QB scoring overwrites no-history priors with NaN",
     "apply_qb_scoring_mode applies its historical join to every QB. A promoted QB without weekly history receives missing season/recent values and forecasts. The stored Stafford surrogate demonstrates this failure in both formats.",
     "The update mask checks position only, not whether joined QB history exists.",
     "Fixed the mask to update only QBs with matched history. A synthetic promoted QB keeps its explicit 18.0 prior and original range. Existing corrupt snapshot files were not rewritten.",
     "Avoids corrupting approved promotion priors. Low risk, isolated empty-join correction.", "No: preserves existing prior methodology and historical-player forecasts.", "dashboard/data.py:apply_qb_scoring_mode"),
    ("P1", "Confirmed interval error", "Zero-clipped floors exceed negative central forecasts",
     "Stored Nick Mullens forecasts are -0.132 in both formats with floor 0; Andy Dalton's four-point forecast is -0.06334 with floor 0. These rows are not public-pool eligible, but the full board violates floor≤central≤ceiling.",
     "Floor clips at zero while the central estimate can legally be negative. Negative fantasy production itself is valid; an inverted interval is not.",
     "Not changed: decide whether to allow negative lower tails or explicitly suppress unsupported low-volume forecasts. The new strict validator blocks publication until resolved.",
     "Protects coherent uncertainty. Moderate risk: changing interval truncation alters documented range methodology.", "Approval required for interval policy, not a reason to force all projections positive.", "dashboard/data.py:apply_qb_scoring_mode, apply_approved_projection_model"),
    ("P1", "Confirmed scoring-display defect", "Six-point QB last-two averages remain four-point values",
     "39 QB rows in the six-point snapshot need a historical-display correction; none need it in four-point mode. All protected forecast and interval columns are identical before and after display repair.",
     "The format converter updates season/recent production but omits last_two_ppr.",
     "Added repair_qb_display_form; invoked during scoring rebuild and once per shared snapshot load. Independent last-two fixture and forecast-preservation tests pass.",
     "Aligns cards and editorial copy with the selected scoring format. Low risk, no per-click recalculation.", "No.", "dashboard/data.py:repair_qb_display_form; dashboard/app.py:get_published_snapshot"),
    ("P1", "Confirmed matchup-display defect", "Trends reverses defense rank direction",
     "Trends sorted adjusted indexes descending and described No. 1 as most favorable; Comparison correctly used ascending/toughest-first. Equal indexes also previously received different ordinal ranks by team name.",
     "Two independent ranking implementations and alphabetic tie-breaking.",
     "Trends now uses opponent_position_rank; equal strengths share the same minimum rank. The denominator explicitly means available distinct defenses, not a guaranteed full 32-team league table.",
     "Makes rank/color interpretation consistent. Low display risk.", "No.", "dashboard/app.py:Player Trends Matchup; dashboard/presentation.py:opponent_position_rank"),
    ("P1", "Confirmed recommendation-display defect", "Unavailable players can receive preferred-start language",
     "The saved eligible pool contains 13 reported-unavailable players in each format. Comparison ranks unchanged baseline points and previously could say START for one of them. Command Center already excludes unavailable bench replacements.",
     "Baseline ranking and actionable availability were not separated in every label.",
     "Unavailable cards and outlooks now say BASELINE ONLY; if the baseline leader is unavailable, Decision Edge says no actionable recommendation. Bench candidates marked data_unavailable are excluded. Sharing images and alternate status spellings still need dedicated end-to-end review.",
     "Reduces false start guidance without erasing research forecasts. Moderate presentation risk; provider statuses can themselves be stale.", "No forecast change; broader availability policy must be reviewed separately.", "dashboard/app.py:comparison verdict; dashboard/outlooks.py:build_player_outlook; dashboard/replacement_optimizer.py:optimize_replacements"),
    ("P1", "Strong modeling concern", "Injury opportunity redistribution lacks role conservation",
     "Optional scenarios redistribute 45% of lost fantasy points across skill players, use a 1.2 same-position affinity, and cap each source boost at min(3 PPR,20%). Multiple sources accumulate; injured nonstarter QBs can each lower all skill estimates.",
     "Fantasy-point pools substitute for carries, routes, targets and snaps; starter status is not enforced on QB injury sources. No validated same-role replacement map is used.",
     "Keep informational-only. Test role-aware, team-constrained scenarios using timestamped depth/routes/snaps before adoption. Do not treat the current factors as medical recovery probabilities.",
     "Potentially improves teammate recommendations; high model/scenario risk and evidence requirements.", "Yes: explicit approval required before changing scenario weights/eligibility.", "dashboard/injury_impact.py:direct_availability_factor, apply_injury_scenario"),
    ("P1", "Confirmed explanation defect", "QB injury penalty explanations are erased",
     "Scenario code writes a teammate passing-outlook penalty but clears all effects when opportunity boost<0.1, including when the team-efficiency factor is below 1.",
     "Explanation cleanup tests only the positive opportunity boost.",
     "Cleanup now clears text only if the team-efficiency factor is exactly 1 as well. A QB-out fixture retains its negative-impact explanation with zero boost.",
     "Explains an existing supplemental result honestly. Low risk; every numeric scenario calculation is unchanged.", "No.", "dashboard/injury_impact.py:apply_injury_scenario"),
    ("P1", "Confirmed methodology-copy mismatch", "Schedule-adjusted rating is not the core opponent input",
     "Core skills use raw positional player-game PPR relative to league mean, capped/sample-scaled. QB uses a separately capped raw QB factor. Trends formerly claimed its schedule-adjusted residual index was the signal used by the projection.",
     "Supplemental descriptive rating and core factor are different columns. Historical residual uses the player's full current-season baseline; it is not a proven causal defense rating.",
     "Corrected Trends copy and editorial adjustment direction to the actual projection_matchup_factor. Test a leakage-safe alternative separately rather than silently swapping the core signal.",
     "Clarifies the model's actual input. Low copy risk; statistical alternative has high validation requirements.", "Copy: no. Changing opponent methodology: approval required.", "dashboard/data.py:build_start_sit_board, apply_approved_projection_model; dashboard/app.py:Trends Matchup; dashboard/outlooks.py"),
    ("P1", "Supported coverage limitation", "No reconciled team stat forecasts exist",
     "Board forecasts PPR directly. Recent opportunities are recorded usage, not projected carries/targets/attempts. Team plays and betting-implied team points are supplemental. There are no projected team targets, dropbacks, red-zone opportunities or player stat allocations to reconcile.",
     "Independent point-regression architecture, with position-level rates and priors rather than a joint offensive-volume model.",
     "Keep accounting checks on raw complete team games. Propose a separate team-first forecasting challenger with coherent passing/receiving TD identities and share allocations. Do not impose arbitrary caps on PPR sums.",
     "Addresses football realism that software tests cannot certify. High model-change risk and new data requirements.", "Yes, proposal only.", "dashboard/data.py:apply_approved_projection_model, add_live_supplementary_context; src/football_qa.py"),
    ("P1", "Confirmed stale-state inconsistency", "Postponed games can be considered started in action rules",
     "Command Center _player_locked honors Postponed/Rescheduled/Cancelled, but action and summary rules independently infer started from the old kickoff.",
     "Duplicated kickoff logic overrides the explicit schedule state.",
     "Shared game_has_started now respects postponed states in action and lineup-status rules. Postponed schedules still require verification/new authoritative kickoff before readiness claims.",
     "Avoids suppressing pregame injury actions solely due to an obsolete time. Low deterministic risk.", "No.", "dashboard/lineup_rules.py:game_has_started, build_lineup_actions, lineup_status"),
    ("P2", "Confirmed labeling/identity defects", "Workload and history labels overstate their meaning",
     "RB opportunities=carries+targets, not touches=carries+receptions. QB attempts+carries omit sacks, so are not dropbacks. Approved recent production uses three games, while outlooks said last four. A legitimate zero last-two average was treated as missing.",
     "Presentation labels drifted from shared field definitions; game logs and Trends used player names instead of stable IDs.",
     "Corrected labels, zero handling, stable-ID game logs/Trends history, and production-versus-role language. The real weekly feed has name collisions (Byron Young and Marcus Harris), though those examples are not public skill-player evidence of a current collision.",
     "Improves trust without changing numeric forecasts. Low risk; legacy no-ID data uses explicit name fallback.", "No.", "dashboard/presentation.py:player_card_stat_summary, player_weekly_history, fantasy_game_log; dashboard/app.py; dashboard/outlooks.py"),
    ("P2", "Confirmed dormant scoring defect", "Raw fallback scorer omits supported categories",
     "Normal data reconciles perfectly because authoritative fantasy_points_ppr is present. If that column disappears, fallback uses interceptions rather than passing_interceptions and omits sack fumbles, two-point conversions and special-teams TDs.",
     "Legacy fallback schema and incomplete scoring weights.",
     "Independent scorer and complete-column validation now expose the gap. Do not silently use the incomplete fallback as a valid production reconstruction; stage a centralized scorer replacement after schema tests.",
     "Prevents degraded feeds from becoming numerically credible forecasts. Medium ingestion risk; current normal forecasts are unaffected.", "No scoring-rule change; implementation replacement not yet applied.", "dashboard/data.py:_position_fantasy_points; src/football_qa.py:independent_ppr"),
    ("P2", "Strong market interpretation concern", "Partial prop totals are not complete expected PPR",
     "implied_ppr accepts any available category and substitutes zero for others. Anytime-TD probability describes ≥1 TD, not expected TD count. The adapter does de-vig yes/no quotes when both are available; a single-sided quote keeps margin. Local snapshot has no published props.",
     "Partial consensus lines and touchdown-event probabilities are combined into one scalar without coverage completeness or event/week keys at normalization.",
     "Corrected methodology disclosure. Add coverage-aware component labels and event/time identity; avoid interpreting the partial value's difference from a complete forecast as an edge.",
     "Makes supplemental information safer. Moderate supplemental-method risk; live provider behavior is unverified here.", "Core: no. Supplemental translation changes need review.", "dashboard/market_expectations.py:implied_ppr, normalize_market_lines; dashboard/providers/sportsdataio.py:flatten_player_props"),
    ("P2", "Supported uncertainty limitation", "Depth and injury freshness do not prove actual availability",
     "QB1 gate checks depth position/order, not report age. Missing injury designation can render no designation even without a personal report. Sleeper fallback accepts some reserve news up to 30 days; Command Center freshness primarily checks retrieval timestamps.",
     "Dataset-level success timestamps and sparse source records stand in for per-player evidence. Suspended is unavailable in replacement/alert rules but not an explicit zero factor in the optional scenario.",
     "Unify status enums and per-player source/freshness evidence; require official inactive verification near kickoff. Returning-from-injury and defensive personnel adjustments need timestamped evidence before model use.",
     "Reduces false reassurance. Moderate/high integration risk; no medical return-date claims should be inferred.", "Availability/UX fixes: no. New numeric injury effects: approval required.", "dashboard/providers/injuries.py; dashboard/data.py:apply_verified_starter_gate; dashboard/lineup_rules.py; dashboard/injury_impact.py"),
    ("P2", "Hypothesis requiring replay", "Latest observed stats week may skip an incomplete NFL week",
     "build_start_sit_board chooses completed_week=max(stat week), then schedules with week>completed_week. A Thursday or partial-week feed can satisfy this condition before all games finish.",
     "Stats presence substitutes for authoritative game completion. The stored audited snapshot is completed Week 4/next Week 5, so this run does not demonstrate a live wrong-week selection.",
     "Replay Thursday/Sunday/Monday cutoffs and reschedules; choose the forecast target using authoritative schedule state and explicit publication cutoff.",
     "Potentially prevents missing current-week comparisons. Moderate pipeline risk; needs schedule replay tests.", "No model weights; week-selection behavior needs staged validation.", "dashboard/data.py:build_start_sit_board"),
]


def main():
    e = json.loads((DEST / "evidence.json").read_text())
    query = "SELECT position, COUNT(*) AS samples, AVG(ABS(target_ppr-incumbent)) AS mae, AVG(target_ppr-incumbent) AS bias_actual_minus_projection, AVG(ABS(target_ppr-regularized_opportunity_efficiency)) AS challenger_mae, 2025 AS test_season FROM benchmark_predictions_2025 GROUP BY position ORDER BY mae DESC"
    connection = duckdb.connect()
    connection.register("benchmark_predictions_2025", pd.read_parquet(ROOT / "reports/model-validation-audit/benchmark-predictions-2025.parquet"))
    historical = connection.execute(query).df().to_dict("records")
    connection.close()
    blocks = []
    def md(identity, heading, text, source=None):
        block = {"id":identity, "type":"markdown", "body":heading+"\n\n"+text}
        if source: block["sourceId"] = source
        blocks.append(block)
    title = "Sunday Decision Lab Football Logic Audit"
    md("title", "# "+title, "")
    md("summary", "## Scoring reconciles, but the snapshot is not ready to certify",
       "The local review found verified display/identity defects and important modeling limitations. Safe fixes are implemented locally; the approved production forecasting weights, scoring rules and numeric injury assumptions have not been changed. **Nothing was deployed.**\n\nThe new strict public-snapshot audit still fails **7 checks**: inverted ranges on low-volume backup rows plus a missing promoted-player forecast in both formats. These are repeated snapshot checks, not seven unique players. Full-PPR raw scoring has **zero mismatches across 4,449 saved weekly rows**, in both four- and six-point passing-TD formats.\n\nPrioritize team/player identity reconciliation, a staged snapshot rebuild and interval policy before release. Software regression tests passing does not establish NFL forecasting accuracy.", "audit")
    md("historic", "## QB evaluation remains the most important modeling follow-up",
       "Recomputed the saved 2025 walk-forward benchmark archive, not new archived pregame forecasts. MAE below means mean absolute error in PPR per player-week. The generic incumbent benchmark has its largest error at QB; its challenger does not improve QB MAE. These are **not** the dedicated live QB formula results and should not be merged with them. Small challenger improvements elsewhere do not justify a model switch.", "history")
    blocks.append({"id":"historical-chart", "type":"chart", "chartId":"mae"})
    blocks.append({"id":"historical-table", "type":"table", "tableId":"history"})
    md("qb", "## Four- and six-point QB evidence must remain separate",
       "The prior dedicated QB evaluation report contains 467 test player-weeks per format: approved-formula MAE 6.741 (four-point) and 8.382 (six-point), with same-position ordering accuracy 59.31% and 58.60%, respectively. These figures were read from the saved report, not independently regenerated from historical raw input in this run. The generic four-position chart has 471 QB rows under a different benchmark definition.\n\nNo evidence in this audit proves realistic backup-start workloads, designed-rush versus scramble allocation, or injury-return behavior. Those require timestamped role/availability evidence and targeted replay.", "qb-history")
    for i, item in enumerate(FINDINGS, 1):
        priority, classification, name, observation, root, correction, impact, authority, location = item
        md(f"finding-{i}", f"## {i}. {name}",
           f"**{priority} · {classification}**\n\n**Evidence / affected calculation:** {observation}\n\n**Root cause:** {root}\n\n**Correction / status:** {correction}\n\n**Expected impact and risk:** {impact}\n\n**Model authority:** {authority}\n\n**Code:** `{location}`", "code")
    md("spec", "## Actual model and input definitions",
       "### Core QB/RB/WR/TE forecasting\n\nSkills combine touchdown-regressed season production (75%) with recent opportunity-rate production (25%). TD regression retains 25% observed TD scoring and replaces 75% with the position opportunity rate. Current-season weight is 40% through two games, 60% through six, 75% through ten, then 90%; a sustained role increase can add 10 percentage points, capped at 90%. Role evidence here is opportunity/share, not routes or first reads. Missing prior history falls back to workload.\n\nQB has a dedicated formula: touchdown and turnover regression, recent three-game attempts/carries/rush yards, prior/league rates and a fading prior anchor; no designed-rush/scramble decomposition. The separate depth-promotion prior is 50% position, 30% team-position and 20% depth role with widened offsets, not a personal-history forecast.\n\n### Input provenance\n\nPublic nflverse weekly player results supply authoritative Full PPR, box scores and stable IDs; schedules supply opponents/week/kickoff. nflverse snapshots also supply snaps and team attempts+carries+sacks as recent plays. Prior-season inputs supply anchors. SportsDataIO supplies depth, weather/game status/totals and props when available. nflverse injury reports are primary, Sleeper fallback/disagreement context is supplemental. Reporting/headshots are nonmodel. Betting team totals use the home-spread convention, not summed fantasy points.\n\n### Recommendations and ranges\n\nComparisons rank central expected PPR; below-two-PPR gaps remain close calls. Command Center replacements maximize total eligible median PPR across slots with unique player assignments (Hungarian assignment); FLEX excludes QB, SUPERFLEX includes QB. Existing stale/missing-data readiness guards remain. The optimizer itself does not require a kickoff timestamp on every caller-supplied candidate, and questionable replacements can still be chosen; verify injury/schedule detail in the interface. Snap participation is not a route-participation forecast. Coaching/scheme, defensive injuries, first-read share and goal-line opportunity are not explicit core inputs.", "code")
    md("accounting", "## Raw team accounting passes; forecast accounting is unavailable",
       "On the complete saved weekly feed, passing and receiving touchdown totals reconcile at team/week grain, and summed targets do not exceed pass attempts. No detected completions>attempts or receptions>targets. Four unattributed non-skill rows are warnings rather than broken selectable identities. Do not drop them from team accounting.\n\n**Not tested as a forecast:** team projected carries, targets, dropbacks, red-zone plays and TD allocation. Those columns do not exist. Adding up independent PPR forecasts is not an accounting identity for real team points. Recent three-game player averages can also cover different calendar games, so their sum is not a contemporaneous team budget.", "audit")
    md("cross", "## Cross-feature checks reuse the same approved board",
       "The evidence file contains a top eligible QB, RB, WR and TE in each scoring format, including stable ID/team/opponent, central points, range, corrected last-two average, shared defense rank and game log. Rankings/Comparison/Trends and Command Center consume the scoring-format board rather than fit separate interaction-time models. All existing forecast/explanation columns are unchanged by the QB display repair.\n\nThis is source- and helper-level agreement, **not a completed browser screenshot matrix**. Share-image availability copy, full roster journeys and mobile visual verification of these latest edits remain release QA tasks. No personal roster data was read or mutated during this audit.", "audit")
    md("testing", "## Permanent rule tests now catch the proven defects",
       "Baseline: 172 tests passed (6.57 seconds). Final local suite: 202 tests passed (26.22 seconds during a concurrent audit run); two pre-existing Pandas future warnings remain. Thirty football-QA tests cover complete scoring/2PT/fumbles, invalid scores/counts/ranges, negative legal yards, complete-feed TD identities, no-history QB promotions, team aliases, tie/rank direction, stable-ID trades, zero recent PPR, injury scenarios, inactive transitions, missing data, bye/locked bench exclusions, FLEX/SUPERFLEX conflicts, conflicting QB1 flags and target/future-outcome mutation in walk-forward features. Fixtures are synthetic rule tests, never live injury claims.\n\nAdded offline `src/football_qa.py`, `scripts/audit_football_logic.py`, `tests/test_football_qa.py` and `football-qa.yml`; inserted strict validation before weekly snapshot publication. Hard errors raise and fail CI. High-priority anomalies and modeling warnings do not automatically reject forecasts. The current strict snapshot run intentionally fails until its remaining data errors are resolved. The workflow is prepared locally, not run on GitHub.")
    md("perf", "## Audit work stays out of user interactions",
       f"The latest isolated offline evidence run took **{e['elapsed_seconds']:.2f} seconds** inside the Python process, excluding interpreter startup; CPU contention changes this result. Across 20 local repetitions per format, QB historical-display repair took **{e['boards']['4']['display_repair_median_ms']:.2f} ms** (four-point) and **{e['boards']['6']['display_repair_median_ms']:.2f} ms** (six-point). It runs once per shared cached snapshot load, not each widget rerun. These are local helper measurements, not Render/mobile response times or a hosting capacity claim. No new paid services or dependencies were introduced.", "audit")
    md("limits", "## What this audit cannot yet certify",
       "The checked-in feed is identified as 2026 Weeks 1–4, published October 8 at 23:31 UTC, forecasting Week 5. No provider refresh or current official availability verification was performed; player statuses cited above describe that saved snapshot only. No historical raw files or timestamped injuries/routes/depth are bundled with the reviewed 2025 prediction archive. Saved error calculations can be reproduced, but backup/rookie/committee/injury subgroup findings cannot be invented from missing role metadata.\n\nWalk-forward source code uses strictly earlier weeks; a synthetic future-outcome mutation test passes. This establishes a tested cutoff property, not complete provenance certification of every saved historical row. Full-season retrospective stat corrections remain a limitation. The saved mixed-position pairwise benchmark includes comparisons that are not ordinary FLEX choices; use eligible-position denominators for future decision-quality claims. P10/P90 coverage was not newly re-estimated. Tail warnings are reviews, not arbitrary workload caps.\n\nThe evidence has 7 hard-check failures, 52 high-priority flags and 328 modeling warnings across two boards and weekly data. These are repeated row/format flags, not independent unique defects; low samples dominate warnings. No empirical-tail claim is made from the current four-week feed.", "audit")
    md("next", "## Approval decisions and the next release checkpoint",
       "1. Approve an interval policy for negative central estimates; retain valid negative fantasy outcomes.\n2. Stage a fresh snapshot after canonical joins, verify promotion identities and stable-ID roster compatibility, then require the strict football gate to pass. Do not rewrite saved user assignments automatically.\n3. Centralize complete raw scoring and canonical status enums; add current-week/Thursday/postponement replay cases.\n4. Keep the round-three model in production. Continue the regularized challenger shadow test for at least four NFL weeks; prioritize dedicated QB evaluation in both formats.\n5. Collect timestamped routes/snaps/first-read, inactive lists and depth changes; only then test role-aware injury redistribution and a team-constrained model against the unchanged baseline.\n6. Finish browser/mobile/share-card QA before any deployment.\n\n**Further questions:** Which negative-tail policy do you want to approve? Can the provider supply stable player IDs and report timestamps for all promotion candidates? What constitutes complete role evidence before supplemental injury estimates become actionable? No production deployment is authorized by this audit.")
    sources = [
        {"id":"audit", "label":"Local football audit evidence", "path":"reports/football-audit-20261009/evidence.json", "query":{"description":"scripts/audit_football_logic.py against checked-in public weekly and 4/6-point boards; exact raw scoring and helper invariants", "metric_definitions":{"mismatch":"abs(independent Full PPR - upstream PPR) > 1e-7", "flag":"One validator flag at row/format grain, not a unique person"}}},
        {"id":"history", "label":"Saved 2025 walk-forward benchmark predictions", "path":"reports/model-validation-audit/benchmark-predictions-2025.parquet", "query":{"sql":query,"engine":"duckdb","tables_used":["benchmark_predictions_2025"],"description":"Local DuckDB registered view of the named saved Parquet archive; one row per position", "metric_definitions":{"mae":"Mean absolute PPR error per saved test player-week", "bias":"Mean actual minus prediction"}}},
        {"id":"qb-history", "label":"Prior dedicated QB scoring evaluation", "path":"reports/model-validation-audit/qb-scoring-format-evaluation.json"},
        {"id":"code", "label":"Reviewed local implementation and regression fixtures", "path":"scripts/build_football_audit_report.py", "query":{"description":"Findings trace dashboard/data.py, presentation.py, app.py, injury_impact.py, providers/sportsdataio.py, providers/injuries.py, outlooks.py, lineup_rules.py, replacement_optimizer.py and src/model_round_two.py; exact functions are listed per finding"}},
        {"id":"nflfastR", "label":"Upstream authoritative raw fantasy-scoring formula", "href":"https://github.com/nflverse/nflfastR/blob/master/R/calculate_stats.R"},
    ]
    artifact = {"surface":"report", "manifest":{"version":1,"title":title,"surface":"report", "blocks":blocks,"sources":sources,
        "charts":[{"id":"mae", "title":"2025 saved benchmark MAE by position", "subtitle":"PPR per player-week; generic incumbent benchmark, not dedicated live QB validation", "type":"bar", "dataset":"historical", "sourceId":"history", "source":sources[1], "encodings":{"x":{"field":"position"},"y":{"field":"mae"}}, "options":{"showLegend":False}}],
        "tables":[{"id":"history", "title":"Saved benchmark samples and errors", "dataset":"historical", "sourceId":"history", "source":sources[1], "columns":[{"field":"position","label":"Position","type":"string"},{"field":"samples","label":"Player-weeks","type":"number"},{"field":"mae","label":"Incumbent MAE","type":"number"},{"field":"challenger_mae","label":"Challenger MAE","type":"number"},{"field":"bias_actual_minus_projection","label":"Actual minus projection","type":"number"}], "defaultSort":{"field":"mae","direction":"desc"}}]},
        "snapshot":{"version":1,"status":"ready","generatedAt":e["as_of"],"datasets":{"historical":historical}}, "sources":sources}
    (DEST / "artifact.json").write_text(json.dumps(artifact, indent=2), encoding="utf-8")
    print(DEST / "artifact.json")


if __name__ == "__main__":
    main()
