[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#69BE28"
backgroundColor = "#F3F6F7"
secondaryBackgroundColor = "#E6ECEF"
textColor = "#071B2C"
font = "sans serif"
